
# Loads default set of integrations. Do not remove.
default_config:

lovelace:
  dashboards:
    front-door:
      mode: yaml
      filename: dashboards/front-door.yaml
      title: Front door
      icon: mdi:home-outline
      show_in_sidebar: true

http:
  ssl_certificate: certs/cert.pem
  ssl_key: certs/privkey.pem
    alex-office:
      mode: yaml
      filename: dashboards/alex-office.yaml
      title: Hubs Office
      icon: mdi:home-outline
      show_in_sidebar: true

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
